name: crm

services:
  backend:
    build:
      context: ./crm-app/backend
      dockerfile: Dockerfile
      platforms: # distinct computing architectures or platforms
        - linux/amd64 # x86_64 - Intel/AMD
        - linux/arm64 # Apple Silicon
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./crm-app/backend/.env.production # Environment variables for production
    environment:
      NODE_ENV: production
    networks:
      - crm_network

  frontend:
    build:
      context: ./crm-app/frontend
      dockerfile: Dockerfile
      platforms: # distinct computing architectures or platforms
        - linux/amd64 # x86_64 - Intel/AMD
        - linux/arm64 # Apple Silicon
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./crm-app/frontend/.env.production # Environment variables for production
    environment:
      NODE_ENV: production
      VITE_API_URL: http://80.225.224.8:3001/api
      VITE_BACKEND_URL: http://80.225.224.8:3001
    networks:
      - crm_network
    depends_on:
      - backend

networks:
  crm_network:
    driver: bridge
