  # version field removed as it is obsolete
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crmdb@21
      POSTGRES_DB: asp_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./crm-app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: ./crm-app/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: asp_crm
      DB_USER: postgres
      DB_PASSWORD: crmdb@21
      JWT_SECRET: 3ef0d123387553c81aaa771f5f62686afd930dece8da511268d4d30e3728b20c83d802dedd6b7caacfa2b94b0f303b3c06414e86d2fd1ca5c7295c0215b53613
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://103.224.243.242:3000
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./crm-app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://103.224.243.242:3001/api
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
