version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crmdb@21
      POSTGRES_DB: asp_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./crm-app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: ./crm-app/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: asp_crm
      DB_USER: postgres
      DB_PASSWORD: crmdb@21
      JWT_SECRET: 3ef0d123387553c81aaa771f5f62686afd930dece8da511268d4d30e3728b20c83d802dedd6b7caacfa2b94b0f303b3c06414e86d2fd1ca5c7295c0215b53613
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://103.224.243.242:3000
      LOG_LEVEL: info
      # AI System Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key_here}
      OPENAI_MODEL: gpt-4o-mini
      OPENAI_MAX_TOKENS: 1000
      OPENAI_TEMPERATURE: 0.7
      OPENAI_TIMEOUT: 2000
      ASP_CRM_BASE_URL: http://backend:3001/api
      ASP_CRM_TIMEOUT: 30000
      LEADS_BYPASS_HEADER: X-bypass-Auth
      LEADS_BYPASS_VALUE: true
      AI_SYSTEM_AUTO_INIT: true
      AI_AGENT_TIMEOUT: 30000
      AI_MAX_CONCURRENT_REQUESTS: 10
      AI_CACHE_ENABLED: true
      AI_CACHE_MAX_SIZE: 1000
      AI_CACHE_TIMEOUT: 300000
      AI_LOG_LEVEL: info
      AI_METRICS_ENABLED: true
      AI_METRICS_INTERVAL: 60000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  frontend:
    build:
      context: ./crm-app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://103.224.243.242:3001/api
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build:
      context: ./crm-app
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
