version: '3.8'
services:
  backend:
    build:
      context: ./crm-app/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      # Add other env vars as needed
    volumes:
      - ./crm-app/backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./crm-app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:3001/api
    depends_on:
      - backend
    volumes:
      - ./crm-app/frontend:/app
    restart: unless-stopped

networks:
  default:
    driver: bridge
