name: crm-postgres-database-dev

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env # Environment variables for development
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dev_postgres_network
    volumes:
      - dev_postgres_data:/var/lib/postgresql
      # Mounting initial schema SQL file for database initialization
      - ./crm-app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev_postgres_network:
    driver: bridge

volumes:
  dev_postgres_data: