name: crm-postgres-database

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.production # Environment variables for production
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crmdb@21}
      POSTGRES_DB: ${POSTGRES_DB:-asp_crm}
    networks:
      - postgres_network
    volumes:
      - postgres_data:/var/lib/postgresql
      # Mounting initial schema SQL file for database initialization
      - ./crm-app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data: