version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    network_mode: host
    environment:
      NODE_ENV: production
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: crmdb@21
      DB_NAME: asp_crm
      PORT: 3001
      ALLOWED_ORIGINS: http://103.224.243.242:3000,http://localhost:3000

  frontend:
    build: ./frontend
    restart: always
    environment:
      VITE_API_URL: http://103.224.243.242:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
